"""Escribe hm-gates.json: los marcadores que piden MO para llegar a ellos.

Mismo formato que gates.json (lo que pide son marcadores de la checklist: la MO
y la medalla que deja usarla fuera de combate), pero por marcador y generado.
"""
import json

# MO -> lo que hace falta tener marcado y como se dice. Igual en los juegos de
# Kanto; la medalla es la que comprueba el juego antes de usarla.
MOVES = {
    'cut': (['HM01', 'Leader Misty'], 'Cut (HM01) and the Cascade Badge', 'Corte (MO01) y la Medalla Cascada'),
    'surf': (['HM03', 'Leader Koga'], 'Surf (HM03) and the Soul Badge', 'Surf (MO03) y la Medalla Alma'),
    'strength': (['HM04', 'Leader Erika'], 'Strength (HM04) and the Rainbow Badge', 'Fuerza (MO04) y la Medalla Arcoíris'),
    'smash': (['HM06', 'Leader Sabrina'], 'Rock Smash (HM06) and the Marsh Badge', 'Golpe Roca (MO06) y la Medalla Pantano'),
    'waterfall': (['HM07', 'Leader Blaine'], 'Waterfall (HM07) and the Volcano Badge', 'Cascada (MO07) y la Medalla Volcán'),
    # Snorlax dormido corta el paso igual que un arbol: se quita con la flauta.
    'flute': (['Poké Flute'], 'the Poké Flute to wake Snorlax', 'la Poké Flauta para despertar a Snorlax'),
}


def write_gates(path, needs, game):
    """needs: {id de marcador: tupla de MO}."""
    groups = {}
    for mid, combo in sorted(needs.items()):
        groups.setdefault(combo, []).append(mid)
    gates = []
    for combo, ids in sorted(groups.items(), key=lambda g: (len(g[0]), g[0])):
        gates.append({
            'id': 'hm-' + '-'.join(combo),
            'markers': ids,
            'needs': [n for mv in combo for n in MOVES[mv][0]],
            'why': {'en': 'Behind an obstacle: ' + ' + '.join(MOVES[mv][1] for mv in combo),
                    'es': 'Detrás de un obstáculo: ' + ' + '.join(MOVES[mv][2] for mv in combo)},
        })
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        json.dump({'_source': f'Generated by the reach scripts from the {game} maps: markers that need these HMs to be reached.',
                   'gates': gates}, f, ensure_ascii=False, indent=1)
        f.write('\n')
    print(f'{path}: {sum(len(g["markers"]) for g in gates)} marcadores en {len(gates)} bloqueos')
