"""Escribe nav.json: la rejilla de cada mapa para calcular rutas en la app.

Comun a todos los juegos. Sale de las mismas `Area` que el analisis de alcance
(reach.py), mas donde se dibuja cada mapa en la app (area e origen en casillas),
su zona y lo que pide cada MO. Con esto la app busca el camino mas corto de donde
estas al siguiente objetivo, con las MO que ya tienes.

Por mapa:
  k: una casilla por byte (base64), fila a fila. Bits 0-2: tipo (muro, suelo,
     agua, cascada, saltos: los de reach.py). Bits 3-6: lados por los que no se
     puede salir (arriba, abajo, izquierda, derecha): los desniveles de la Gen 1.
  e: altura de cada casilla (FRLG), un byte por casilla; sin ella, no hay alturas.
  ob: obstaculos [x, y, MO]. wp: puertas [x, y, mapa, puerta]. dr: donde se
  aparece al llegar por cada puerta. cn: bordes [lado, desplazamiento, mapa].
Y del juego: starts, donde empieza la partida; ferry, los muelles de un barco
que une todos entre si (las Islas Sete).
"""
import base64, json

from common.reach import STEPS


def _blocked(a, x, y):
    """Lados por los que no se sale de (x, y) por una pareja de tiles (Gen 1)."""
    bits = 0
    if not a.pairs:
        return bits
    for i, (dx, dy) in enumerate(STEPS):
        nx, ny = x + dx, y + dy
        if 0 <= nx < a.w and 0 <= ny < a.h:
            t, nt = a.tiles[y][x], a.tiles[ny][nx]
            if (t, nt) in a.pairs or (nt, t) in a.pairs:
                bits |= 1 << i
    return bits


def write_nav(path, areas, placed, moves, starts=(), ferry=()):
    """placed: {mapa: (zona, area de la app, x, y)} solo de los mapas que se dibujan."""
    out = {}
    for mid, (zone, area, ox, oy) in placed.items():
        a = areas.get(mid)
        if a is None:
            continue
        k = bytes(a.kind[y][x] | _blocked(a, x, y) << 3 for y in range(a.h) for x in range(a.w))
        m = {'zone': zone, 'area': area, 'x': ox, 'y': oy, 'w': a.w, 'h': a.h, 'k': base64.b64encode(k).decode()}
        if a.elev is not None:
            m['e'] = base64.b64encode(bytes(min(v, 15) for row in a.elev for v in row)).decode()
        if a.obstacles:
            m['ob'] = [[x, y, mv] for (x, y), mv in sorted(a.obstacles.items())]
        wp = [[x, y, dest, k] for x, y, dest, k in a.warps if dest in placed]
        if wp:
            m['wp'] = wp
        if a.doors:
            m['dr'] = [list(d) for d in a.doors]
        cn = [[s, off, dest] for s, off, dest in a.connections if dest in placed]
        if cn:
            m['cn'] = cn
        out[mid] = m
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        json.dump({'_source': 'Generated by the reach scripts: walkable grid of every map, for routes in the app.',
                   'moves': {mv: needs for mv, (needs, _, _) in moves.items()},
                   'starts': [list(s) for s in starts], 'ferry': [list(s) for s in ferry], 'maps': out},
                  f, ensure_ascii=False, separators=(',', ':'))
    print(f'{path}: {len(out)} mapas')
